[workspace]
members = [
    "bin/cli",

    "lib",
]

[workspace.dependencies]
hemtt-pbo = { git = "https://github.com/brettmayson/hemtt" }
rayon = "1.7.0"
serde = { version = "1.0.162", features = ["derive"] }
