[package]
name = "harmony-app"
version = "0.0.0"
description = "Arma 3 Mod Manager for Communities"
authors = ["Brett Mayson <brett@mayson.io>"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[dependencies]
dirs = "5.0.1"
rmp-serde = { version = "1.1.1" }
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
steamlocate = { git = "https://github.com/LovecraftianHorror/steamlocate-rs/", branch = "fully-switch-from-steamy-vdf" }
tauri = { version = "1.3.0", features = ["dialog-message", "dialog-open", "shell-open"] }
uuid = { version = "1.3.2", features = ["v4", "serde"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
