[package]
name = "harmony-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "harmony"
path = "src/main.rs"

[dependencies]
harmony = { path = "../../lib" }
tokio = { workspace = true, features = ["full"] }

clap = { version = "4.1.8", features = ["derive"] }
rayon = { workspace = true }
tokio-rayon = "2.1.0"
